apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: USERNAME
spec:
  request: <CSR (Base64 encoded)>
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 86400000 #Validation period
  usages:
  - client auth
