---
- name: setting up k8s cluster
  hosts: all
  become: true
  tasks:
    - name: Setting the basis on all nodes
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/pre_setup
        - $PWD/roles/pre_k8s_setup
        - $PWD/roles/install_crio
        - $PWD/roles/Install_Helm
      when: "mode != 'haproxy'"


    - name: install kubeadm and kubectl
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/install_kube_adm_ctl_let
      when: "mode != 'haproxy'"


    - name: Run role on haproxy host
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/haproxy
        - $PWD/roles/pre_setup
      when: "'haproxy' in mode"



    - name: Run role on first host in hosts group
      include_role:
        name: $PWD/roles/init_k8s
      when: "'true' in init_master"


- name: join workers and masters
  hosts: all
  become: true
  serial: 1
  tasks:
    - name: Run role on other master hosts
      include_role:
        name: $PWD/roles/join_masters
      when: mode == 'master' and init_master == 'false'

    - name: Run role on worker hosts
      include_role:
        name: $PWD/roles/join_workers
      when: "'worker' in mode"


- name: Set up CNI and CSI
  become: true
  serial: 1
  hosts: all
  tasks:
    - name: Install Calico
      include_role:
        name: $PWD/roles/CNI_Calico
      when: mode == 'master' and init_master == 'true'

    - name: Install the Openebs Helm chart
      include_role:
        name: $PWD/roles/SDS_Openebs_Cstore/Openebs_Helm
      when: mode == 'master' and init_master == 'true'


    - name: Generate the required resources for Openebs (Cstore mode)
      include_role:
        name: $PWD/roles/SDS_Openebs_Cstore/Cstore_Config
      when: mode == 'master' and init_master == 'true'


    - name: Install the Openebs resources
      include_role:
        name: $PWD/roles/SDS_Openebs_Cstore/Apply_Openebs_Resources
      when: mode == 'master' and init_master == 'true'


- name: Make the cluster operation ready
  become: true
  serial: 1
  hosts: all
  tasks:
    - name: Automatic ETCD backup on S3
      include_role:
        name: $PWD/roles/Automate_Etcd_Backup_Setup/Backup_Cron_Job
      when: mode == 'master'

    - name: Installing ingress controller
      include_role:
        name: $PWD/roles/Ingress
      when: mode == 'master' and init_master == 'true'

    - name: Installing Cert Manager
      include_role:
        name: $PWD/roles/Cert_manager
      when: mode == 'master' and init_master == 'true'

    - name: Change the binding address of services so prometheus would be able to scrape data
      shell:
        cmd: "{{ item }}"
      with_items:
        - sed -e 's/--bind-address=127.0.0.1/--bind-address=0.0.0.0/' -i /etc/kubernetes/manifests/kube-scheduler.yaml
        - sed -e 's/--bind-address=127.0.0.1/--bind-address=0.0.0.0/' -i /etc/kubernetes/manifests/kube-controller-manager.yaml
      when: mode == 'master'

    - name: Installing Monitoring for the cluster
      include_role:
        name: $PWD/roles/Monitoring
      when: mode == 'master' and init_master == 'true'



- name: Implement backup procedure for etcd
  become: true
  hosts: all
  tasks:
    - name: Configuring connection with S3bucket
      include_role:
        name: $PWD/roles/Automate_Etcd_Backup_Setup/Configure_S3cmd
      when: mode == 'master'

    - name: Adding a cron job to backup ETCD
      include_role:
        name: $PWD/roles/Automate_Etcd_Backup_Setup/Backup_Cron_Job
      when: mode == 'master'


