---
- name: join workers and masters
  hosts: all
  become: true
  serial: 1
  tasks:
    - name: Update kubeadm on the first master
      include_role:
        name: $PWD/roles/Upgrade_Master/Update_Kubeadm_First_Master
      when: mode == 'master' and init_master == 'true'

    - name: Run role on other master hosts
      include_role:
        name: $PWD/roles/Upgrade_Master/Update_Kubeadm_Other_Masters
      when: mode == 'master' and init_master == 'false'

    - name: Run role on other master hosts
      include_role:
        name: $PWD/roles/Upgrade_Master/Update_Kubectl_Kubelet_Master
      when: mode == 'master'

