all:
    children:
        kang:
            hosts:  
                master-kang-1:
                    ansible_host:
                    ansible_user: root
                    mode: 'master'
                    init_master: 'true'
                master-kang-2:
                    ansible_host:
                    ansible_user: root
                    mode: 'master'
                    init_master: 'false'
                master-kang-3:
                    ansible_host:
                    ansible_user: root
                    mode: 'master'
                    init_master: 'false'



                worker-kang-1:
                    ansible_host:
                    ansible_user: root
                    mode: 'worker'
                    init_master: 'false'
                worker-kang-2:
                    ansible_host:
                    ansible_user: root
                    mode: 'worker'
                    init_master: 'false'
                worker-kang-3:
                    ansible_host:
                    ansible_user: root
                    mode: 'worker'
                    init_master: 'false'



                haproxy:
                    ansible_host:
                    ansible_user: root
                    mode: 'haproxy'
                    init_master: 'false'



