---

- name: Apply The cspc for Openebs
  kubernetes.core.k8s:
    src: "/root/openebs_config/cspc.yaml"
    state: present
    apply: true
    kubeconfig: /etc/kubernetes/admin.conf


- name: Waiting for the operator so it would finish up its set up
  pause:
    seconds: 20


- name: Apply the storage class for the cluster
  kubernetes.core.k8s:
    src: "/root/openebs_config/Storage_Class.yaml"
    state: present
    apply: true
    kubeconfig: /etc/kubernetes/admin.conf


#- name: Make kang-sc the default storage class for all PVCs
#  shell: kubectl patch storageclass kang-sc -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
#  failed_when: false
