---
- name: check connectivity
  ping:
    data: alive


- name: update repos
  apt:
    update_cache: yes
    allow_downgrade: yes

- name: Unhold kubeadm for updating
  dpkg_selections:
    name: kubeadm
    selection: install


- name: Update kubeadm version
  apt:
    name: kubeadm=1.26.0-00
    state: present


- name: Hold the packages to prevent accidental updates
  dpkg_selections:
    name: kubeadm
    selection: hold


- name: Upgrade kubeadm on master node
  shell:
    cmd: kubeadm upgrade node --dry-run
  register: upgrade_master_result


- name: Echo the result of upgrade kubeadm
  debug:
    var: upgrade_master_result


- name: Check to proceed to upgrade master nodes
  pause:
    prompt: "Proceed if everything is alright"

- name: Upgrade kubeadm on master node
  shell:
    cmd: kubeadm upgrade node --dry-run
  register: actual_upgrade_master_result

- name: Echo the result of actual upgrade kubeadm
  debug:
    var: actual_upgrade_master_result


#apt update
#
#
#
#
#apt-mark unhold kubeadm
#
# apt-get update && apt-get install -y kubeadm=1.26.x-00 && \
#
# apt-mark hold kubeadm
#
#kubeadm upgrade plan
#kubectl drain <node-to-drain> --ignore-daemonsets
#
#apt-mark unhold kubelet kubectl && \
#apt-get update && apt-get install -y kubelet=1.26.x-00 kubectl=1.26.x-00 && \
#apt-mark hold kubelet kubectl
#sudo systemctl daemon-reload
#sudo systemctl restart kubelet
#
#kubectl uncordon <node-to-uncordon>



