---
- name: check connectivity
  ping:
    data: alive


- name: update and upgrade system
  apt:
    update_cache: yes


- name: Install Etcdctl
  apt:
    pkg:
      - etcd-client
    state: present


- name: Backing up (Full) ETCD every first minute of every hour
  ansible.builtin.cron:
    name: "Etcd Backup"
    weekday: "*"
    minute: "25"
    hour: "*"
    day: "*"
    cron_file: etcd_back_up_kang
    user: root
    job: "ETCDCTL_API=3 etcdctl --endpoints=https://127.0.0.1:2379 --cacert=/etc/kubernetes/pki/etcd/ca.crt --cert=/etc/kubernetes/pki/etcd/server.crt --key=/etc/kubernetes/pki/etcd/server.key snapshot save /data/etcd-backup/etcd-snapshot-$(hostname)-$(date +%Y-%m-%dT%H:%M).db & s3cmd put -r /data/etcd-backup/ s3://kangetcdbackup"
    state: present




