---
- name: Create a directory for openebs
  file:
    path: /root/openebs_config
    state: directory
    mode: 0744
    group: root
    owner: root

- name: Copy the files to the directory
  copy:
    dest: /root/openebs_config
    src: files/openebs
    force: true

- name: Verify if helm is installed on the system
  shell:
    cmd: helm version
  register: helm_check
  failed_when: "'version.BuildInfo' not in helm_check.stdout"
  changed_when: false


- name: Install storage controller on the cluster
  kubernetes.core.helm:
    name: openebs
    chart_ref: /root/openebs_config/openebs
    wait: true
    release_state: present
    values_files: "/root/openebs_config/openebs/values.yaml"
    release_namespace: "openebs"
    atomic: true
    create_namespace: true






